version: '3.8'
services:
  lannister_db:
    image: postgres:14
    container_name: lannister_db
    hostname: localhost
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
  web:
    build: ./Lannister/api_src
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - lannister_db
